//! On-disk persistence (TOML) for rules approved with `permanent` lifetime.
//!
//! The file is pyloros-authored — never hand-edited. Writing is atomic
//! via tempfile + rename. Reading is a straight `toml::from_str` into a
//! `Config::rules`-compatible shape.

use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::config::Rule;

use super::types::ApprovalError;

#[derive(Serialize)]
struct RulesFileOut<'a> {
    #[serde(rename = "rules")]
    rules: &'a [Rule],
}

#[derive(Deserialize)]
struct RulesFileIn {
    #[serde(default)]
    rules: Vec<Rule>,
}

/// Load permanent rules from the permanent-rules file. If the file does not
/// exist, returns an empty vector — that's the normal startup case
/// before the first permanent approval has been granted.
pub fn load_permanent_rules(path: impl AsRef<Path>) -> Result<Vec<Rule>, ApprovalError> {
    let path = path.as_ref();
    if !path.exists() {
        return Ok(Vec::new());
    }
    let text = std::fs::read_to_string(path)?;
    let loaded: RulesFileIn =
        toml::from_str(&text).map_err(|e| ApprovalError::TomlDe(e.to_string()))?;
    Ok(loaded.rules)
}

/// Atomically rewrite the permanent-rules file to contain exactly `rules`. The
/// caller holds the full in-memory list of permanent rules and passes it
/// here; we overwrite rather than append so the file stays in sync with
/// state (e.g. future revokes just re-write without the revoked rule).
pub fn save_permanent_rules(path: impl AsRef<Path>, rules: &[Rule]) -> Result<(), ApprovalError> {
    let path = path.as_ref();
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent)?;

    let body = toml::to_string(&RulesFileOut { rules })
        .map_err(|e| ApprovalError::TomlSer(e.to_string()))?;
    let mut doc = String::from(
        "# Auto-generated by pyloros. Delete this file to revoke all permanent approvals.\n\n",
    );
    doc.push_str(&body);

    let mut tmp = tempfile::NamedTempFile::new_in(parent)?;
    tmp.write_all(doc.as_bytes())?;
    tmp.flush()?;
    tmp.persist(path).map_err(|e| e.error)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use pyloros_test_support::test_report;

    fn rule(method: &str, url: &str) -> Rule {
        Rule {
            method: Some(method.to_string()),
            url: url.to_string(),
            websocket: false,
            git: None,
            branches: None,
            allow_redirects: Vec::new(),
            log_body: false,
        }
    }

    #[test]
    fn load_from_missing_path_returns_empty() {
        let t = test_report!("load_permanent_rules: missing file returns empty");
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("nope.toml");
        let rules = load_permanent_rules(&p).unwrap();
        t.assert_eq("empty", &rules.len(), &0usize);
    }

    #[test]
    fn save_then_load_roundtrip() {
        let t = test_report!("save_permanent_rules roundtrips through load");
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("approvals.toml");
        let rules = vec![
            rule("GET", "https://api.foo.com/*"),
            rule("POST", "https://api.bar.com/v1/*"),
        ];
        save_permanent_rules(&p, &rules).unwrap();
        let loaded = load_permanent_rules(&p).unwrap();
        t.assert_eq("count", &loaded.len(), &2usize);
        t.assert_eq(
            "first url",
            &loaded[0].url.as_str(),
            &"https://api.foo.com/*",
        );
        t.assert_eq(
            "second method",
            &loaded[1].method.as_deref().unwrap(),
            &"POST",
        );
    }
}
